### PR TITLE
Simulate Lambda Proxy Integration

### PR DESCRIPTION
**Pull request by ktonon**
http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html#api-gateway-create-api-as-simple-proxy-for-lambda-build

### CODE REVIEW

**Comment by ktonon** [comment]
Oops, I see another PR addressing the same issue: #80

**Comment by HyperBrain** [comment]
@ktonon It would be great if you could comment in #135 if you use the serve functionality or not, so that we can decide how to proceed there.

**Comment by ktonon** [comment]
@HyperBrain Just reviewed #135, `serverless-offline` is a great option. I've switched to that without any issues. I'm ok with closing this PR. Thanks!

**Comment by HyperBrain** [comment]
`serve` will be removed in the next `v3.0.0` release in favor of `serverless-offline` (see #152 ). No efforts will be spent on the function anymore. So I'll close this issue.

**Pull request closed without merging**
