### PR TITLE
Expose service and options for dynamicity

### LINKED ISSUE #158: Is it possible to dynamically configure the WebPack configuration (e.g. to do Tree Shaking)?
# This is a Question

## Description
How can I tell webpack to do some Tree Shaking? When I import modules, I might not want the whole thing, but just a function, usually I would just execute webpack in production mode with the -p option, but doesn't seem there is a way to do this here.

### PR DESCRIPTION
**Pull request by kikar**
## What did you implement:

Closes #158 

## Todos:

- [x] Write tests
- [x] Write documentation
- Fix linting errors (not yet implemented)
- Make sure code coverage hasn't dropped (not yet implemented)
- Provide verification config / commands / resources
- Enable "Allow edits from maintainers" for this PR
- Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by kikar** [comment]
@HyperBrain opened a PR, could you help me with the documentation and testing?

**Comment by HyperBrain** [comment]
Will have a look later today and review the changes 😃

**Comment by kikar** [comment]
I realised now that if we expose the serverless and the option, we dont really need the entries anymore.
Does it make sense to remove it?

**Comment by HyperBrain** [comment]
Not really. Entries contain the entry points needed for the actual Serverless run. It will also honor single function deployments. We should not move this functionality (that guarantees that it is set correctly) to the webpack configuration. Later on (when we fully support individual packaging, so that tree shaking is applied via multi-compile to let each function be optimized separately) entries must be completely under the control of the plugin.

With the new service and options export, it is in the developer's hand, if he wants to change the default behavior - with the risk of breaking things or over-engineering :) But the default behavior should be as simple as possible, so that any user can just enable the plugin, use lib.entries and is done.

**Comment by kikar** [comment]
Example of my `webpack.config.js`.
Thanks to the `servicePath` it can stay in the root folder and not in every service.
```javascript
const slsw = require('serverless-webpack');
const { join } = require('path');
const UglifyPlugin = require('webpack').optimize.UglifyJsPlugin;

let entry = slsw.lib.entries;
for (let key in entry) {
  entry[key] = entry[key] + '.ts';
}

let servicePath = slsw.lib.serverless.config.servicePath;
let plugins = [];

if (slsw.lib.options.stage === 'prod') {
  plugins.push(new UglifyPlugin()); // Tree Shaking FTW!
}

module.exports = {
  entry,
  target: 'node',
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'ts-loader' }
    ]
  },
  resolve: {
    extensions: ['.ts', '.js']
  },
  output: {
    path: join(slsw.lib.serverless.config.servicePath, '.webpack'),
    libraryTarget: 'commonjs',
    filename: '[name].js'
  },
  plugins
}
```

**Comment by HyperBrain** [comment]
This looks good.

> let entry = slsw.lib.entries;
> for (let key in entry) {
>   entry[key] = entry[key] + '.ts';
> }

This will be obsolete if we do a file search and determine the correct handler extension in #167 instead of forcing the user to add code to his webpack conf to get it run.

In general, I think that your example (after the extension changes in #167 have been done) can be added to the examples folder as (typescript-with-dynamic configuration).

I will add the missing unit tests here and merge this after the other PR.

**Comment by kikar** [comment]
> This will be obsolete if we do a file search and determine the correct handler extension in #167 instead of forcing the user to add code to his webpack conf to get it run.
I think that it can get complicated, but also gives less space for customisation. Imagine a situation where the developer wants to write a function in .ts and one in .js

It's only 4 lines of code that we're talking about in the end.

**Comment by HyperBrain** [comment]
But everyone has to add them - exactly in the same way. The framework should do that properly (and can do that because it is deterministic).

**Comment by HyperBrain** [comment]
I added unit tests and will update the README too. Then this should be good to go 😃 .

**Pull request merged**
