### PR TITLE
Add support for -d option (to generate source-maps)

### PR DESCRIPTION
**Pull request by StefH**
- Add support for -d option (to generate source-maps)
- Fix tests on Windows 7/10 (Note that 2 tests still fail ?)

### CODE REVIEW

**Comment by thenikso** [comment]
I'd lave that to the webpack configuration itself. I don't really see a value added in having an option. What's your use case?

**Comment by StefH** [comment]
I want to use your project as:

`"build:webpack": "rimraf ./dist && serverless webpack --out dist -d"`

Which will also build the source-maps.

**Comment by hassankhan** [comment]
I tend to agree with @thenikso here, this is something I'd prefer my configuration to handle.

**Comment by HyperBrain** [comment]
The webpack config now has access to the whole Serverless context and options. You can use these now to enable sourcemap support dynamically in your config. You even can react on any (new) options you might introduce in your environment by using the exported `lib.options` object.

```js
// webpack.conf.js
const slsw = require('serverless-webpack');

// This will check for a non standard CLI option --debug
const isDebug = slsw.lib.options.debug;

// Or you can make it dependent on the currently deployed stage
const isDebug = slsw.lib.options.stage === 'dev';

// Or even anything available in the current Serverless execution context
const isDebug = slsw.lib.serverless.XXXXXXXXX;
```

Closing this PR now as it is now possible to write fully dynamic webpack configurations.

**Pull request closed without merging**
