### PR TITLE
Add hook for deploying individual functions

### PR DESCRIPTION
**Pull request by johnf**
As discussed in #60

### CODE REVIEW

**Comment by mhodgson** [comment]
I can verify that this works. Would love to get this merged.

**Comment by mhodgson** [comment]
Actually @johnf, I think you need to add `.then(this.packExternalModules)` as well for this to work for functions with external modules.

**Comment by johnf** [comment]
@mhodgson you're right. Have just fixed that

**Comment by deathweaselx86** [comment]
This would be wonderful.

**Comment by kiawins** [comment]
Would also love to see some docs go along with this PR to understand how it could be used.

**Comment by johnf** [comment]
Hi Kia,

It's nothing specific to serverless-webpack, it is just enabling standard serverless functionality.

i.e. making sure that ```sls deploy function -f functionName``` works. This is a lot faster as it just re-publishes the new code to Lambda and doesn't run cloudformation.

Docs at https://serverless.com/framework/docs/providers/aws/cli-reference/deploy-function/

**Comment by johnf** [comment]
@thenikso any chance of getting this merged for another rc before 1.0.0 release?

**Comment by blakedietz** [comment]
Any chance we could pull this in?

**Comment by SkippyZA** [comment]
Also would really like to get this in asap.

**Comment by SkippyZA** [comment]
@thenikso is there any word on this PR? Would like to try avoid needing to fork this :/

**Comment by ShaunEgan** [comment]
Would also really love this to be merged.

**Comment by hassankhan** [comment]
Big +1, getting `Code storage exceeded` errors from AWS 😢

**Comment by HyperBrain** [comment]
@hassankhan 
> Big +1, getting Code storage exceeded errors from AWS

I think that's worth an issue in Serverless. The reason most likely is, that SLS does set the DeletionPolicy of the deployed function versions to "Retain", which will never delete any deployed version. Then you'll run out of code storage sooner or later.

**Comment by hassankhan** [comment]
I'm not quite sure where the bug is, @HyperBrain 😕 . Spent most of last night trying to repair things as there was an issue with bundling. I have 19 functions, which together add up to 40MB. 

With `package.individually = false`, it seems that the deployment ZIP gets uploaded 19 times to Lambda. When setting it to `true`, it creates 19 ZIPs, but unfortunately inside the ZIP all 19 functions are present.

I started getting those errors, and incorrectly assumed it was to do with individual Lambda size. After much tinkering with Webpack, I reduced individual function size but continued to receive the same error on various functions upon CloudFormation deploy.

I finally clued onto the fact that I'd hit the 75GB hard limit by going to the Web Console and clicking Lambda. However, the Console was reporting total Lambda size as just over 1GB. It was then when I remembered that all functions are kept unless pruned, but at this point CloudFormation was stuck in a `UPDATE_REQUIRES_ACTION` state.

After fixing that, I was finally able to remove the stack and redeploy. I'm still looking into why the packaging is weird - for now the only fix I have is to use [serverless-prune-plugin](https://github.com/claygregory/serverless-prune-plugin) till I figure it out.

**Comment by HyperBrain** [comment]
@johnf @mhodgson @blakedietz @SkippyZA @ShaunEgan @deathweaselx86 @hassankhan 
According to the comment in (https://github.com/elastic-coders/serverless-webpack/pull/130#issuecomment-312349755) this PR is superseded - as it seems that the ZIP file is not copied to the sls temp dir correctly. Can you please check if #130 works for you? I'd like to merge that then in favor of this one.

**Comment by johnf** [comment]
I think I commented in one of the others that I also prefer #130. I didn't close this for some reason though!
Will do so now.

**Pull request closed without merging**
