### PR TITLE
Update webpack version from 1.3.x to 2.2.1

### PR DESCRIPTION
**Pull request by AKIRA-MIYAKE**
For complicated applications using type scripts, webpack 2 is more sophisticated and convenient.

### CODE REVIEW

**Comment by Gomah** [comment]
It's a breaking change, another PR https://github.com/elastic-coders/serverless-webpack/pull/83 was just merged about it.

**Comment by domaslasauskas** [comment]
Good point Gomah. I jumped the gun by merging #83 as looking at it now it was a breaking change too, I'll be reverting/replacing it with a version range instead. I'm planing to go through the backlog by fixing issues/taking pull requests over upcoming weeks.

**Comment by HyperBrain** [comment]
@domaslasauskas I'm planning to get out a stable update with the most needed fixes as soon as possible.
What is your opinion about the merged #83 . Although it might be a breaking change (as the including project has to specify a webpack version as peer dependency - we currently even use master with Webpack 3 without problems) I'm not really sure what side-effects or update problems might arise additionally.
Can you give a short statement about that?

**Comment by hassankhan** [comment]
Not to disparage @AKIRA-MIYAKE's work, but is this PR relevant after #83? I'd be in favour of closing, since we can now specify what version we need ourselves.

**Comment by HyperBrain** [comment]
Closing this, as the next release (v 2.0.0) adds Webpack as peer dependency and allows any Webpack version to be used.

**Pull request closed without merging**
