### PR TITLE
Rewrite relative local npm package.json dependencies to work when ins…

### PR DESCRIPTION
**Pull request by mattsills**
…talled in the dist directory

### CODE REVIEW

**Comment by jdbevan** [comment]
It would be nice if there was some kind of automated test to go with this, but the code looks good and I need this fix too, so +1 :)

**Comment by hassankhan** [comment]
Is this still an issue? I've used relative paths for package dependencies in the past and don't remember having this problem.

**Comment by HyperBrain** [comment]
@mattsills Could you please give an update (see @hassankhan 's question)? Please verify it with version 2.2.0.

**Comment by HyperBrain** [comment]
I will close this PR now - there hasn't been any response for some weeks now. We should check if `file:` dependencies work in V3 and open a new issue if they do not. As the codebase has changed a completely new fix is appropriate then.

**Pull request closed without merging**
