### PR TITLE
Pack external packages into distribution for deploy command and --out option

### PR DESCRIPTION
**Pull request by cyyuen**
User could define custom key, includePackages to indicate which packages they want to pack into the final distribution:

```yaml
custom:
   includePackages:
      - package1
      - package2
```

### CODE REVIEW

**Comment by thenikso** [comment]
This is very cool! Would you have time to add an example in the `examples` and some lines in the readme?

**Comment by cyyuen** [comment]
Sure. @thenikso . I have added an example and some lines in readme. Could you help me to review it? Thanks.

**Comment by thenikso** [comment]
Brilliant, it seams all well done to me. I tried it and it is a much needed addition.

My only concern would be the `includePackages` naming for the custom option not conveying the meaning. I'd think of adding "webpack" somewhere to connect the option with this plugin. Like `webpackIncludePackages` or `webpackIncludeModules` or `webpackBundleModules` what do you think?

I'll release `1.0.0-beta.2.2` when this is ready (I'll keep beta 3 for when the same Serverless beta is out).

Amazing work 🎉

**Comment by cyyuen** [comment]
I agree. I think `webpackIncludeModules ` is the best.

**Comment by thenikso** [comment]
done 🎉 🎉 🎉

**Comment by cyyuen** [comment]
Awesome. Thanks! 🎉 🎉 🎉

**Pull request merged**
