### PR TITLE
Make webpack a peer dependency so that webpack 2 can be used

### PR DESCRIPTION
**Pull request by rvaidya**
Sorry for the wait

### CODE REVIEW

**Comment by hassankhan** [comment]
Any updates on this?

**Comment by borisirota** [comment]
Hi @domaslasauskas 

Can you update `npm` with the latest version which supports this PR ?

Thanks !

**Comment by jamesandersen** [comment]
I just ran into a really nasty issue where I was trying to load a .json file.   Running webpack normally worked fine but compiling with `serverless webpack` failed with an error.   After eventually debugging through the serverless webpack code and forcing it to output the webpack version I discovered the version mismatch.   I had webpack 2.2.1 installed globally but the serverless plugin was using 1.14 and causing my error.

I'm anxiously awaiting a new version on `npm` with this fix...

**Comment by patoncrispy** [comment]
@jamesandersen this will get you what you need in the meantim: `yarn add --dev https://github.com/elastic-coders/serverless-webpack/tarball/master`.

**Pull request merged**
